- name: Copy the files to the machine.
  synchronize:
    src: "../../../../"
    dest: "/home/{{ ansible_user }}/src/"
  tags:
    - update

- name: Install system dependencies
  apt:
    name: "{{ item }}"
  loop:
    - python3-dev
    - python3-cryptography
    - libjpeg-dev
    - libfreetype6-dev
    - libtiff-dev
    - libwebp-dev
    - liblcms2-dev
    - zlib1g-dev
    - nginx
    - libssl-dev
    - libffi-dev
  become: yes

- name: Pre-install pip and setuptools
  pip:
    name: "{{ item }}"
    virtualenv: "/home/{{ ansible_user }}/pyenv"
  loop:
    - setuptools>=37
    - pip>=9

- name: Install ledslie dependencies
  pip:
    requirements: "/home/{{ ansible_user }}/src/requirements.txt"
    virtualenv: "/home/{{ ansible_user }}/pyenv"

- name: Install the Ledslie software.
  command: "/home/{{ ansible_user }}/pyenv/bin/python setup.py install"
  args:
    chdir: "/home/{{ ansible_user }}/src/"
  tags:
    - update

- name: Installing /etc/default/ledslie
  template:
    src: defaults-ledslie
    dest: /etc/default/ledslie
  become: yes

- name: Create logging directory
  file:
    name: /var/log/ledslie
    state: directory
    owner: www-data
    group: www-data
    mode: 0770
  become: yes

- name: Installing systemd templates
  template:
    src: ledslie-site.service
    dest: /etc/systemd/system/ledslie-site.service
  become: yes
  tags:
    - systemd

- name: Start ledslie site services
  systemd:
    name: ledslie-site
    state: restarted
    enabled: yes
  become: yes
  tags:
    - update
    - systemd

- name: Copy nginx configuration
  template:
    src: nginx-ledslie.conf
    dest: /etc/nginx/sites-available/ledslie.conf
  become: yes

- name: Enabling nginx Ledslie configuration
  file:
    state: link
    path:  /etc/nginx/sites-enabled/ledslie.conf
    src: /etc/nginx/sites-available/ledslie.conf
  become: yes

- name: Removing nginx default site
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  become: yes

- name: Restart nginx.
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: yes
  tags:
    - systemd
